server:
  port: 8071
spring:
  application:
    name: config-server
  profiles:
    active: git
  threads:
    virtual:
      enabled: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MaivMinh/e-commerce-config
          default-label: main
          timeout: 10
          clone-on-start: true
          force-pull: true
          username: MaivMinh

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    # Readiness and liveness configurations.
    readinees-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probe:
        enabled: true