version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: keycloak
    command: ["start-dev"]  # dev mode disables HTTPS requirement
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    volumes:
      - ./keycloak-providers:/opt/keycloak/providers
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - postgres
    ports:
      - "9090:8080"

volumes:
  postgres_data:
  keycloak_data:
