// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.grpc.product_service;

public interface CartItemFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.CartItemField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cartItemId = 1;</code>
   * @return The cartItemId.
   */
  java.lang.String getCartItemId();
  /**
   * <code>string cartItemId = 1;</code>
   * @return The bytes for cartItemId.
   */
  com.google.protobuf.ByteString
      getCartItemIdBytes();

  /**
   * <code>string productVariantId = 2;</code>
   * @return The productVariantId.
   */
  java.lang.String getProductVariantId();
  /**
   * <code>string productVariantId = 2;</code>
   * @return The bytes for productVariantId.
   */
  com.google.protobuf.ByteString
      getProductVariantIdBytes();
}
