// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.grpc.product_service;

public interface FindProductVariantsByIdsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.FindProductVariantsByIdsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
   */
  java.util.List<com.minh.grpc.product_service.CartItemField> 
      getCartItemFieldList();
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
   */
  com.minh.grpc.product_service.CartItemField getCartItemField(int index);
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
   */
  int getCartItemFieldCount();
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
   */
  java.util.List<? extends com.minh.grpc.product_service.CartItemFieldOrBuilder> 
      getCartItemFieldOrBuilderList();
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
   */
  com.minh.grpc.product_service.CartItemFieldOrBuilder getCartItemFieldOrBuilder(
      int index);
}
