// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.grpc.product_service;

public interface FindProductVariantByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.FindProductVariantByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
   * @return Whether the productVariant field is set.
   */
  boolean hasProductVariant();
  /**
   * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
   * @return The productVariant.
   */
  com.minh.grpc.product_service.ProductVariant getProductVariant();
  /**
   * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
   */
  com.minh.grpc.product_service.ProductVariantOrBuilder getProductVariantOrBuilder();
}
