// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.grpc.product_service;

/**
 * Protobuf type {@code net.devh.boot.grpc.example.ProductVariant}
 */
public final class ProductVariant extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:net.devh.boot.grpc.example.ProductVariant)
    ProductVariantOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductVariant.newBuilder() to construct.
  private ProductVariant(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductVariant() {
    id_ = "";
    name_ = "";
    slug_ = "";
    size_ = "";
    colorName_ = "";
    colorHex_ = "";
    cover_ = "";
    cartItemId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductVariant();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_ProductVariant_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_ProductVariant_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.minh.grpc.product_service.ProductVariant.class, com.minh.grpc.product_service.ProductVariant.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SLUG_FIELD_NUMBER = 3;
  private volatile java.lang.Object slug_;
  /**
   * <code>string slug = 3;</code>
   * @return The slug.
   */
  @java.lang.Override
  public java.lang.String getSlug() {
    java.lang.Object ref = slug_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      slug_ = s;
      return s;
    }
  }
  /**
   * <code>string slug = 3;</code>
   * @return The bytes for slug.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSlugBytes() {
    java.lang.Object ref = slug_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      slug_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIZE_FIELD_NUMBER = 4;
  private volatile java.lang.Object size_;
  /**
   * <code>string size = 4;</code>
   * @return The size.
   */
  @java.lang.Override
  public java.lang.String getSize() {
    java.lang.Object ref = size_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      size_ = s;
      return s;
    }
  }
  /**
   * <code>string size = 4;</code>
   * @return The bytes for size.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSizeBytes() {
    java.lang.Object ref = size_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      size_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLORNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object colorName_;
  /**
   * <code>string colorName = 5;</code>
   * @return The colorName.
   */
  @java.lang.Override
  public java.lang.String getColorName() {
    java.lang.Object ref = colorName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      colorName_ = s;
      return s;
    }
  }
  /**
   * <code>string colorName = 5;</code>
   * @return The bytes for colorName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getColorNameBytes() {
    java.lang.Object ref = colorName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      colorName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLORHEX_FIELD_NUMBER = 6;
  private volatile java.lang.Object colorHex_;
  /**
   * <code>string colorHex = 6;</code>
   * @return The colorHex.
   */
  @java.lang.Override
  public java.lang.String getColorHex() {
    java.lang.Object ref = colorHex_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      colorHex_ = s;
      return s;
    }
  }
  /**
   * <code>string colorHex = 6;</code>
   * @return The bytes for colorHex.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getColorHexBytes() {
    java.lang.Object ref = colorHex_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      colorHex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COVER_FIELD_NUMBER = 7;
  private volatile java.lang.Object cover_;
  /**
   * <code>string cover = 7;</code>
   * @return The cover.
   */
  @java.lang.Override
  public java.lang.String getCover() {
    java.lang.Object ref = cover_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cover_ = s;
      return s;
    }
  }
  /**
   * <code>string cover = 7;</code>
   * @return The bytes for cover.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCoverBytes() {
    java.lang.Object ref = cover_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cover_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 8;
  private double price_;
  /**
   * <code>double price = 8;</code>
   * @return The price.
   */
  @java.lang.Override
  public double getPrice() {
    return price_;
  }

  public static final int ORIGINALPRICE_FIELD_NUMBER = 9;
  private double originalPrice_;
  /**
   * <code>double originalPrice = 9;</code>
   * @return The originalPrice.
   */
  @java.lang.Override
  public double getOriginalPrice() {
    return originalPrice_;
  }

  public static final int CARTITEMID_FIELD_NUMBER = 10;
  private volatile java.lang.Object cartItemId_;
  /**
   * <code>string cartItemId = 10;</code>
   * @return The cartItemId.
   */
  @java.lang.Override
  public java.lang.String getCartItemId() {
    java.lang.Object ref = cartItemId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cartItemId_ = s;
      return s;
    }
  }
  /**
   * <code>string cartItemId = 10;</code>
   * @return The bytes for cartItemId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCartItemIdBytes() {
    java.lang.Object ref = cartItemId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cartItemId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(slug_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, slug_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(size_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, size_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(colorName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, colorName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(colorHex_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, colorHex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cover_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, cover_);
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      output.writeDouble(8, price_);
    }
    if (java.lang.Double.doubleToRawLongBits(originalPrice_) != 0) {
      output.writeDouble(9, originalPrice_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cartItemId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, cartItemId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(slug_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, slug_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(size_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, size_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(colorName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, colorName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(colorHex_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, colorHex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cover_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, cover_);
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, price_);
    }
    if (java.lang.Double.doubleToRawLongBits(originalPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, originalPrice_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cartItemId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, cartItemId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.minh.grpc.product_service.ProductVariant)) {
      return super.equals(obj);
    }
    com.minh.grpc.product_service.ProductVariant other = (com.minh.grpc.product_service.ProductVariant) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getSlug()
        .equals(other.getSlug())) return false;
    if (!getSize()
        .equals(other.getSize())) return false;
    if (!getColorName()
        .equals(other.getColorName())) return false;
    if (!getColorHex()
        .equals(other.getColorHex())) return false;
    if (!getCover()
        .equals(other.getCover())) return false;
    if (java.lang.Double.doubleToLongBits(getPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getOriginalPrice())
        != java.lang.Double.doubleToLongBits(
            other.getOriginalPrice())) return false;
    if (!getCartItemId()
        .equals(other.getCartItemId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + SLUG_FIELD_NUMBER;
    hash = (53 * hash) + getSlug().hashCode();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize().hashCode();
    hash = (37 * hash) + COLORNAME_FIELD_NUMBER;
    hash = (53 * hash) + getColorName().hashCode();
    hash = (37 * hash) + COLORHEX_FIELD_NUMBER;
    hash = (53 * hash) + getColorHex().hashCode();
    hash = (37 * hash) + COVER_FIELD_NUMBER;
    hash = (53 * hash) + getCover().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + ORIGINALPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getOriginalPrice()));
    hash = (37 * hash) + CARTITEMID_FIELD_NUMBER;
    hash = (53 * hash) + getCartItemId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.minh.grpc.product_service.ProductVariant parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc.product_service.ProductVariant parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc.product_service.ProductVariant parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc.product_service.ProductVariant parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc.product_service.ProductVariant parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc.product_service.ProductVariant parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc.product_service.ProductVariant parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minh.grpc.product_service.ProductVariant parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minh.grpc.product_service.ProductVariant parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.minh.grpc.product_service.ProductVariant parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minh.grpc.product_service.ProductVariant parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minh.grpc.product_service.ProductVariant parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.minh.grpc.product_service.ProductVariant prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code net.devh.boot.grpc.example.ProductVariant}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:net.devh.boot.grpc.example.ProductVariant)
      com.minh.grpc.product_service.ProductVariantOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_ProductVariant_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_ProductVariant_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.minh.grpc.product_service.ProductVariant.class, com.minh.grpc.product_service.ProductVariant.Builder.class);
    }

    // Construct using com.minh.grpc.product_service.ProductVariant.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      name_ = "";

      slug_ = "";

      size_ = "";

      colorName_ = "";

      colorHex_ = "";

      cover_ = "";

      price_ = 0D;

      originalPrice_ = 0D;

      cartItemId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_ProductVariant_descriptor;
    }

    @java.lang.Override
    public com.minh.grpc.product_service.ProductVariant getDefaultInstanceForType() {
      return com.minh.grpc.product_service.ProductVariant.getDefaultInstance();
    }

    @java.lang.Override
    public com.minh.grpc.product_service.ProductVariant build() {
      com.minh.grpc.product_service.ProductVariant result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.minh.grpc.product_service.ProductVariant buildPartial() {
      com.minh.grpc.product_service.ProductVariant result = new com.minh.grpc.product_service.ProductVariant(this);
      result.id_ = id_;
      result.name_ = name_;
      result.slug_ = slug_;
      result.size_ = size_;
      result.colorName_ = colorName_;
      result.colorHex_ = colorHex_;
      result.cover_ = cover_;
      result.price_ = price_;
      result.originalPrice_ = originalPrice_;
      result.cartItemId_ = cartItemId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.minh.grpc.product_service.ProductVariant) {
        return mergeFrom((com.minh.grpc.product_service.ProductVariant)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.minh.grpc.product_service.ProductVariant other) {
      if (other == com.minh.grpc.product_service.ProductVariant.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getSlug().isEmpty()) {
        slug_ = other.slug_;
        onChanged();
      }
      if (!other.getSize().isEmpty()) {
        size_ = other.size_;
        onChanged();
      }
      if (!other.getColorName().isEmpty()) {
        colorName_ = other.colorName_;
        onChanged();
      }
      if (!other.getColorHex().isEmpty()) {
        colorHex_ = other.colorHex_;
        onChanged();
      }
      if (!other.getCover().isEmpty()) {
        cover_ = other.cover_;
        onChanged();
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (other.getOriginalPrice() != 0D) {
        setOriginalPrice(other.getOriginalPrice());
      }
      if (!other.getCartItemId().isEmpty()) {
        cartItemId_ = other.cartItemId_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              slug_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              size_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              colorName_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              colorHex_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 58: {
              cover_ = input.readStringRequireUtf8();

              break;
            } // case 58
            case 65: {
              price_ = input.readDouble();

              break;
            } // case 65
            case 73: {
              originalPrice_ = input.readDouble();

              break;
            } // case 73
            case 82: {
              cartItemId_ = input.readStringRequireUtf8();

              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object slug_ = "";
    /**
     * <code>string slug = 3;</code>
     * @return The slug.
     */
    public java.lang.String getSlug() {
      java.lang.Object ref = slug_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        slug_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string slug = 3;</code>
     * @return The bytes for slug.
     */
    public com.google.protobuf.ByteString
        getSlugBytes() {
      java.lang.Object ref = slug_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        slug_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string slug = 3;</code>
     * @param value The slug to set.
     * @return This builder for chaining.
     */
    public Builder setSlug(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      slug_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string slug = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlug() {
      
      slug_ = getDefaultInstance().getSlug();
      onChanged();
      return this;
    }
    /**
     * <code>string slug = 3;</code>
     * @param value The bytes for slug to set.
     * @return This builder for chaining.
     */
    public Builder setSlugBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      slug_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object size_ = "";
    /**
     * <code>string size = 4;</code>
     * @return The size.
     */
    public java.lang.String getSize() {
      java.lang.Object ref = size_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        size_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string size = 4;</code>
     * @return The bytes for size.
     */
    public com.google.protobuf.ByteString
        getSizeBytes() {
      java.lang.Object ref = size_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        size_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string size = 4;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string size = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      
      size_ = getDefaultInstance().getSize();
      onChanged();
      return this;
    }
    /**
     * <code>string size = 4;</code>
     * @param value The bytes for size to set.
     * @return This builder for chaining.
     */
    public Builder setSizeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      size_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object colorName_ = "";
    /**
     * <code>string colorName = 5;</code>
     * @return The colorName.
     */
    public java.lang.String getColorName() {
      java.lang.Object ref = colorName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        colorName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string colorName = 5;</code>
     * @return The bytes for colorName.
     */
    public com.google.protobuf.ByteString
        getColorNameBytes() {
      java.lang.Object ref = colorName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        colorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string colorName = 5;</code>
     * @param value The colorName to set.
     * @return This builder for chaining.
     */
    public Builder setColorName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      colorName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string colorName = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearColorName() {
      
      colorName_ = getDefaultInstance().getColorName();
      onChanged();
      return this;
    }
    /**
     * <code>string colorName = 5;</code>
     * @param value The bytes for colorName to set.
     * @return This builder for chaining.
     */
    public Builder setColorNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      colorName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object colorHex_ = "";
    /**
     * <code>string colorHex = 6;</code>
     * @return The colorHex.
     */
    public java.lang.String getColorHex() {
      java.lang.Object ref = colorHex_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        colorHex_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string colorHex = 6;</code>
     * @return The bytes for colorHex.
     */
    public com.google.protobuf.ByteString
        getColorHexBytes() {
      java.lang.Object ref = colorHex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        colorHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string colorHex = 6;</code>
     * @param value The colorHex to set.
     * @return This builder for chaining.
     */
    public Builder setColorHex(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      colorHex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string colorHex = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearColorHex() {
      
      colorHex_ = getDefaultInstance().getColorHex();
      onChanged();
      return this;
    }
    /**
     * <code>string colorHex = 6;</code>
     * @param value The bytes for colorHex to set.
     * @return This builder for chaining.
     */
    public Builder setColorHexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      colorHex_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cover_ = "";
    /**
     * <code>string cover = 7;</code>
     * @return The cover.
     */
    public java.lang.String getCover() {
      java.lang.Object ref = cover_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cover_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cover = 7;</code>
     * @return The bytes for cover.
     */
    public com.google.protobuf.ByteString
        getCoverBytes() {
      java.lang.Object ref = cover_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cover_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cover = 7;</code>
     * @param value The cover to set.
     * @return This builder for chaining.
     */
    public Builder setCover(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cover_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cover = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCover() {
      
      cover_ = getDefaultInstance().getCover();
      onChanged();
      return this;
    }
    /**
     * <code>string cover = 7;</code>
     * @param value The bytes for cover to set.
     * @return This builder for chaining.
     */
    public Builder setCoverBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cover_ = value;
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <code>double price = 8;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }
    /**
     * <code>double price = 8;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double price = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0D;
      onChanged();
      return this;
    }

    private double originalPrice_ ;
    /**
     * <code>double originalPrice = 9;</code>
     * @return The originalPrice.
     */
    @java.lang.Override
    public double getOriginalPrice() {
      return originalPrice_;
    }
    /**
     * <code>double originalPrice = 9;</code>
     * @param value The originalPrice to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalPrice(double value) {
      
      originalPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double originalPrice = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalPrice() {
      
      originalPrice_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object cartItemId_ = "";
    /**
     * <code>string cartItemId = 10;</code>
     * @return The cartItemId.
     */
    public java.lang.String getCartItemId() {
      java.lang.Object ref = cartItemId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cartItemId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cartItemId = 10;</code>
     * @return The bytes for cartItemId.
     */
    public com.google.protobuf.ByteString
        getCartItemIdBytes() {
      java.lang.Object ref = cartItemId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cartItemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cartItemId = 10;</code>
     * @param value The cartItemId to set.
     * @return This builder for chaining.
     */
    public Builder setCartItemId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cartItemId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cartItemId = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCartItemId() {
      
      cartItemId_ = getDefaultInstance().getCartItemId();
      onChanged();
      return this;
    }
    /**
     * <code>string cartItemId = 10;</code>
     * @param value The bytes for cartItemId to set.
     * @return This builder for chaining.
     */
    public Builder setCartItemIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cartItemId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:net.devh.boot.grpc.example.ProductVariant)
  }

  // @@protoc_insertion_point(class_scope:net.devh.boot.grpc.example.ProductVariant)
  private static final com.minh.grpc.product_service.ProductVariant DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.minh.grpc.product_service.ProductVariant();
  }

  public static com.minh.grpc.product_service.ProductVariant getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductVariant>
      PARSER = new com.google.protobuf.AbstractParser<ProductVariant>() {
    @java.lang.Override
    public ProductVariant parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProductVariant> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductVariant> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.minh.grpc.product_service.ProductVariant getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

