// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.grpc.product_service;

public interface ProductVariantOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.ProductVariant)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string slug = 3;</code>
   * @return The slug.
   */
  java.lang.String getSlug();
  /**
   * <code>string slug = 3;</code>
   * @return The bytes for slug.
   */
  com.google.protobuf.ByteString
      getSlugBytes();

  /**
   * <code>string size = 4;</code>
   * @return The size.
   */
  java.lang.String getSize();
  /**
   * <code>string size = 4;</code>
   * @return The bytes for size.
   */
  com.google.protobuf.ByteString
      getSizeBytes();

  /**
   * <code>string colorName = 5;</code>
   * @return The colorName.
   */
  java.lang.String getColorName();
  /**
   * <code>string colorName = 5;</code>
   * @return The bytes for colorName.
   */
  com.google.protobuf.ByteString
      getColorNameBytes();

  /**
   * <code>string colorHex = 6;</code>
   * @return The colorHex.
   */
  java.lang.String getColorHex();
  /**
   * <code>string colorHex = 6;</code>
   * @return The bytes for colorHex.
   */
  com.google.protobuf.ByteString
      getColorHexBytes();

  /**
   * <code>string cover = 7;</code>
   * @return The cover.
   */
  java.lang.String getCover();
  /**
   * <code>string cover = 7;</code>
   * @return The bytes for cover.
   */
  com.google.protobuf.ByteString
      getCoverBytes();

  /**
   * <code>double price = 8;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>double originalPrice = 9;</code>
   * @return The originalPrice.
   */
  double getOriginalPrice();

  /**
   * <code>string cartItemId = 10;</code>
   * @return The cartItemId.
   */
  java.lang.String getCartItemId();
  /**
   * <code>string cartItemId = 10;</code>
   * @return The bytes for cartItemId.
   */
  com.google.protobuf.ByteString
      getCartItemIdBytes();
}
