// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.grpc.product_service;

/**
 * Protobuf type {@code net.devh.boot.grpc.example.FindProductVariantsByIdsRequest}
 */
public final class FindProductVariantsByIdsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:net.devh.boot.grpc.example.FindProductVariantsByIdsRequest)
    FindProductVariantsByIdsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FindProductVariantsByIdsRequest.newBuilder() to construct.
  private FindProductVariantsByIdsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FindProductVariantsByIdsRequest() {
    cartItemField_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FindProductVariantsByIdsRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.minh.grpc.product_service.FindProductVariantsByIdsRequest.class, com.minh.grpc.product_service.FindProductVariantsByIdsRequest.Builder.class);
  }

  public static final int CARTITEMFIELD_FIELD_NUMBER = 1;
  private java.util.List<com.minh.grpc.product_service.CartItemField> cartItemField_;
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.minh.grpc.product_service.CartItemField> getCartItemFieldList() {
    return cartItemField_;
  }
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.minh.grpc.product_service.CartItemFieldOrBuilder> 
      getCartItemFieldOrBuilderList() {
    return cartItemField_;
  }
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
   */
  @java.lang.Override
  public int getCartItemFieldCount() {
    return cartItemField_.size();
  }
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
   */
  @java.lang.Override
  public com.minh.grpc.product_service.CartItemField getCartItemField(int index) {
    return cartItemField_.get(index);
  }
  /**
   * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
   */
  @java.lang.Override
  public com.minh.grpc.product_service.CartItemFieldOrBuilder getCartItemFieldOrBuilder(
      int index) {
    return cartItemField_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < cartItemField_.size(); i++) {
      output.writeMessage(1, cartItemField_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < cartItemField_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, cartItemField_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.minh.grpc.product_service.FindProductVariantsByIdsRequest)) {
      return super.equals(obj);
    }
    com.minh.grpc.product_service.FindProductVariantsByIdsRequest other = (com.minh.grpc.product_service.FindProductVariantsByIdsRequest) obj;

    if (!getCartItemFieldList()
        .equals(other.getCartItemFieldList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCartItemFieldCount() > 0) {
      hash = (37 * hash) + CARTITEMFIELD_FIELD_NUMBER;
      hash = (53 * hash) + getCartItemFieldList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.minh.grpc.product_service.FindProductVariantsByIdsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc.product_service.FindProductVariantsByIdsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc.product_service.FindProductVariantsByIdsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc.product_service.FindProductVariantsByIdsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc.product_service.FindProductVariantsByIdsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc.product_service.FindProductVariantsByIdsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc.product_service.FindProductVariantsByIdsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minh.grpc.product_service.FindProductVariantsByIdsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minh.grpc.product_service.FindProductVariantsByIdsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.minh.grpc.product_service.FindProductVariantsByIdsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minh.grpc.product_service.FindProductVariantsByIdsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minh.grpc.product_service.FindProductVariantsByIdsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.minh.grpc.product_service.FindProductVariantsByIdsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code net.devh.boot.grpc.example.FindProductVariantsByIdsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:net.devh.boot.grpc.example.FindProductVariantsByIdsRequest)
      com.minh.grpc.product_service.FindProductVariantsByIdsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.minh.grpc.product_service.FindProductVariantsByIdsRequest.class, com.minh.grpc.product_service.FindProductVariantsByIdsRequest.Builder.class);
    }

    // Construct using com.minh.grpc.product_service.FindProductVariantsByIdsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (cartItemFieldBuilder_ == null) {
        cartItemField_ = java.util.Collections.emptyList();
      } else {
        cartItemField_ = null;
        cartItemFieldBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_descriptor;
    }

    @java.lang.Override
    public com.minh.grpc.product_service.FindProductVariantsByIdsRequest getDefaultInstanceForType() {
      return com.minh.grpc.product_service.FindProductVariantsByIdsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.minh.grpc.product_service.FindProductVariantsByIdsRequest build() {
      com.minh.grpc.product_service.FindProductVariantsByIdsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.minh.grpc.product_service.FindProductVariantsByIdsRequest buildPartial() {
      com.minh.grpc.product_service.FindProductVariantsByIdsRequest result = new com.minh.grpc.product_service.FindProductVariantsByIdsRequest(this);
      int from_bitField0_ = bitField0_;
      if (cartItemFieldBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          cartItemField_ = java.util.Collections.unmodifiableList(cartItemField_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cartItemField_ = cartItemField_;
      } else {
        result.cartItemField_ = cartItemFieldBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.minh.grpc.product_service.FindProductVariantsByIdsRequest) {
        return mergeFrom((com.minh.grpc.product_service.FindProductVariantsByIdsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.minh.grpc.product_service.FindProductVariantsByIdsRequest other) {
      if (other == com.minh.grpc.product_service.FindProductVariantsByIdsRequest.getDefaultInstance()) return this;
      if (cartItemFieldBuilder_ == null) {
        if (!other.cartItemField_.isEmpty()) {
          if (cartItemField_.isEmpty()) {
            cartItemField_ = other.cartItemField_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCartItemFieldIsMutable();
            cartItemField_.addAll(other.cartItemField_);
          }
          onChanged();
        }
      } else {
        if (!other.cartItemField_.isEmpty()) {
          if (cartItemFieldBuilder_.isEmpty()) {
            cartItemFieldBuilder_.dispose();
            cartItemFieldBuilder_ = null;
            cartItemField_ = other.cartItemField_;
            bitField0_ = (bitField0_ & ~0x00000001);
            cartItemFieldBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCartItemFieldFieldBuilder() : null;
          } else {
            cartItemFieldBuilder_.addAllMessages(other.cartItemField_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.minh.grpc.product_service.CartItemField m =
                  input.readMessage(
                      com.minh.grpc.product_service.CartItemField.parser(),
                      extensionRegistry);
              if (cartItemFieldBuilder_ == null) {
                ensureCartItemFieldIsMutable();
                cartItemField_.add(m);
              } else {
                cartItemFieldBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.minh.grpc.product_service.CartItemField> cartItemField_ =
      java.util.Collections.emptyList();
    private void ensureCartItemFieldIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        cartItemField_ = new java.util.ArrayList<com.minh.grpc.product_service.CartItemField>(cartItemField_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.minh.grpc.product_service.CartItemField, com.minh.grpc.product_service.CartItemField.Builder, com.minh.grpc.product_service.CartItemFieldOrBuilder> cartItemFieldBuilder_;

    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public java.util.List<com.minh.grpc.product_service.CartItemField> getCartItemFieldList() {
      if (cartItemFieldBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cartItemField_);
      } else {
        return cartItemFieldBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public int getCartItemFieldCount() {
      if (cartItemFieldBuilder_ == null) {
        return cartItemField_.size();
      } else {
        return cartItemFieldBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public com.minh.grpc.product_service.CartItemField getCartItemField(int index) {
      if (cartItemFieldBuilder_ == null) {
        return cartItemField_.get(index);
      } else {
        return cartItemFieldBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public Builder setCartItemField(
        int index, com.minh.grpc.product_service.CartItemField value) {
      if (cartItemFieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartItemFieldIsMutable();
        cartItemField_.set(index, value);
        onChanged();
      } else {
        cartItemFieldBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public Builder setCartItemField(
        int index, com.minh.grpc.product_service.CartItemField.Builder builderForValue) {
      if (cartItemFieldBuilder_ == null) {
        ensureCartItemFieldIsMutable();
        cartItemField_.set(index, builderForValue.build());
        onChanged();
      } else {
        cartItemFieldBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public Builder addCartItemField(com.minh.grpc.product_service.CartItemField value) {
      if (cartItemFieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartItemFieldIsMutable();
        cartItemField_.add(value);
        onChanged();
      } else {
        cartItemFieldBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public Builder addCartItemField(
        int index, com.minh.grpc.product_service.CartItemField value) {
      if (cartItemFieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartItemFieldIsMutable();
        cartItemField_.add(index, value);
        onChanged();
      } else {
        cartItemFieldBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public Builder addCartItemField(
        com.minh.grpc.product_service.CartItemField.Builder builderForValue) {
      if (cartItemFieldBuilder_ == null) {
        ensureCartItemFieldIsMutable();
        cartItemField_.add(builderForValue.build());
        onChanged();
      } else {
        cartItemFieldBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public Builder addCartItemField(
        int index, com.minh.grpc.product_service.CartItemField.Builder builderForValue) {
      if (cartItemFieldBuilder_ == null) {
        ensureCartItemFieldIsMutable();
        cartItemField_.add(index, builderForValue.build());
        onChanged();
      } else {
        cartItemFieldBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public Builder addAllCartItemField(
        java.lang.Iterable<? extends com.minh.grpc.product_service.CartItemField> values) {
      if (cartItemFieldBuilder_ == null) {
        ensureCartItemFieldIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cartItemField_);
        onChanged();
      } else {
        cartItemFieldBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public Builder clearCartItemField() {
      if (cartItemFieldBuilder_ == null) {
        cartItemField_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        cartItemFieldBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public Builder removeCartItemField(int index) {
      if (cartItemFieldBuilder_ == null) {
        ensureCartItemFieldIsMutable();
        cartItemField_.remove(index);
        onChanged();
      } else {
        cartItemFieldBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public com.minh.grpc.product_service.CartItemField.Builder getCartItemFieldBuilder(
        int index) {
      return getCartItemFieldFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public com.minh.grpc.product_service.CartItemFieldOrBuilder getCartItemFieldOrBuilder(
        int index) {
      if (cartItemFieldBuilder_ == null) {
        return cartItemField_.get(index);  } else {
        return cartItemFieldBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public java.util.List<? extends com.minh.grpc.product_service.CartItemFieldOrBuilder> 
         getCartItemFieldOrBuilderList() {
      if (cartItemFieldBuilder_ != null) {
        return cartItemFieldBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cartItemField_);
      }
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public com.minh.grpc.product_service.CartItemField.Builder addCartItemFieldBuilder() {
      return getCartItemFieldFieldBuilder().addBuilder(
          com.minh.grpc.product_service.CartItemField.getDefaultInstance());
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public com.minh.grpc.product_service.CartItemField.Builder addCartItemFieldBuilder(
        int index) {
      return getCartItemFieldFieldBuilder().addBuilder(
          index, com.minh.grpc.product_service.CartItemField.getDefaultInstance());
    }
    /**
     * <code>repeated .net.devh.boot.grpc.example.CartItemField cartItemField = 1;</code>
     */
    public java.util.List<com.minh.grpc.product_service.CartItemField.Builder> 
         getCartItemFieldBuilderList() {
      return getCartItemFieldFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.minh.grpc.product_service.CartItemField, com.minh.grpc.product_service.CartItemField.Builder, com.minh.grpc.product_service.CartItemFieldOrBuilder> 
        getCartItemFieldFieldBuilder() {
      if (cartItemFieldBuilder_ == null) {
        cartItemFieldBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.minh.grpc.product_service.CartItemField, com.minh.grpc.product_service.CartItemField.Builder, com.minh.grpc.product_service.CartItemFieldOrBuilder>(
                cartItemField_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        cartItemField_ = null;
      }
      return cartItemFieldBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:net.devh.boot.grpc.example.FindProductVariantsByIdsRequest)
  }

  // @@protoc_insertion_point(class_scope:net.devh.boot.grpc.example.FindProductVariantsByIdsRequest)
  private static final com.minh.grpc.product_service.FindProductVariantsByIdsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.minh.grpc.product_service.FindProductVariantsByIdsRequest();
  }

  public static com.minh.grpc.product_service.FindProductVariantsByIdsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FindProductVariantsByIdsRequest>
      PARSER = new com.google.protobuf.AbstractParser<FindProductVariantsByIdsRequest>() {
    @java.lang.Override
    public FindProductVariantsByIdsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FindProductVariantsByIdsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FindProductVariantsByIdsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.minh.grpc.product_service.FindProductVariantsByIdsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

