// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.grpc.product_service;

/**
 * Protobuf type {@code net.devh.boot.grpc.example.FindProductVariantByIdResponse}
 */
public final class FindProductVariantByIdResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:net.devh.boot.grpc.example.FindProductVariantByIdResponse)
    FindProductVariantByIdResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FindProductVariantByIdResponse.newBuilder() to construct.
  private FindProductVariantByIdResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FindProductVariantByIdResponse() {
    message_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FindProductVariantByIdResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.minh.grpc.product_service.FindProductVariantByIdResponse.class, com.minh.grpc.product_service.FindProductVariantByIdResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTVARIANT_FIELD_NUMBER = 3;
  private com.minh.grpc.product_service.ProductVariant productVariant_;
  /**
   * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
   * @return Whether the productVariant field is set.
   */
  @java.lang.Override
  public boolean hasProductVariant() {
    return productVariant_ != null;
  }
  /**
   * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
   * @return The productVariant.
   */
  @java.lang.Override
  public com.minh.grpc.product_service.ProductVariant getProductVariant() {
    return productVariant_ == null ? com.minh.grpc.product_service.ProductVariant.getDefaultInstance() : productVariant_;
  }
  /**
   * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
   */
  @java.lang.Override
  public com.minh.grpc.product_service.ProductVariantOrBuilder getProductVariantOrBuilder() {
    return getProductVariant();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != 0) {
      output.writeInt32(1, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (productVariant_ != null) {
      output.writeMessage(3, getProductVariant());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (productVariant_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getProductVariant());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.minh.grpc.product_service.FindProductVariantByIdResponse)) {
      return super.equals(obj);
    }
    com.minh.grpc.product_service.FindProductVariantByIdResponse other = (com.minh.grpc.product_service.FindProductVariantByIdResponse) obj;

    if (getStatus()
        != other.getStatus()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (hasProductVariant() != other.hasProductVariant()) return false;
    if (hasProductVariant()) {
      if (!getProductVariant()
          .equals(other.getProductVariant())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasProductVariant()) {
      hash = (37 * hash) + PRODUCTVARIANT_FIELD_NUMBER;
      hash = (53 * hash) + getProductVariant().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.minh.grpc.product_service.FindProductVariantByIdResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc.product_service.FindProductVariantByIdResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc.product_service.FindProductVariantByIdResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc.product_service.FindProductVariantByIdResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc.product_service.FindProductVariantByIdResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minh.grpc.product_service.FindProductVariantByIdResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minh.grpc.product_service.FindProductVariantByIdResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minh.grpc.product_service.FindProductVariantByIdResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minh.grpc.product_service.FindProductVariantByIdResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.minh.grpc.product_service.FindProductVariantByIdResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minh.grpc.product_service.FindProductVariantByIdResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minh.grpc.product_service.FindProductVariantByIdResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.minh.grpc.product_service.FindProductVariantByIdResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code net.devh.boot.grpc.example.FindProductVariantByIdResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:net.devh.boot.grpc.example.FindProductVariantByIdResponse)
      com.minh.grpc.product_service.FindProductVariantByIdResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.minh.grpc.product_service.FindProductVariantByIdResponse.class, com.minh.grpc.product_service.FindProductVariantByIdResponse.Builder.class);
    }

    // Construct using com.minh.grpc.product_service.FindProductVariantByIdResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      status_ = 0;

      message_ = "";

      if (productVariantBuilder_ == null) {
        productVariant_ = null;
      } else {
        productVariant_ = null;
        productVariantBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.minh.grpc.product_service.ProductProto.internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_descriptor;
    }

    @java.lang.Override
    public com.minh.grpc.product_service.FindProductVariantByIdResponse getDefaultInstanceForType() {
      return com.minh.grpc.product_service.FindProductVariantByIdResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.minh.grpc.product_service.FindProductVariantByIdResponse build() {
      com.minh.grpc.product_service.FindProductVariantByIdResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.minh.grpc.product_service.FindProductVariantByIdResponse buildPartial() {
      com.minh.grpc.product_service.FindProductVariantByIdResponse result = new com.minh.grpc.product_service.FindProductVariantByIdResponse(this);
      result.status_ = status_;
      result.message_ = message_;
      if (productVariantBuilder_ == null) {
        result.productVariant_ = productVariant_;
      } else {
        result.productVariant_ = productVariantBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.minh.grpc.product_service.FindProductVariantByIdResponse) {
        return mergeFrom((com.minh.grpc.product_service.FindProductVariantByIdResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.minh.grpc.product_service.FindProductVariantByIdResponse other) {
      if (other == com.minh.grpc.product_service.FindProductVariantByIdResponse.getDefaultInstance()) return this;
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.hasProductVariant()) {
        mergeProductVariant(other.getProductVariant());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              status_ = input.readInt32();

              break;
            } // case 8
            case 18: {
              message_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getProductVariantFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int status_ ;
    /**
     * <code>int32 status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>int32 status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private com.minh.grpc.product_service.ProductVariant productVariant_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minh.grpc.product_service.ProductVariant, com.minh.grpc.product_service.ProductVariant.Builder, com.minh.grpc.product_service.ProductVariantOrBuilder> productVariantBuilder_;
    /**
     * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
     * @return Whether the productVariant field is set.
     */
    public boolean hasProductVariant() {
      return productVariantBuilder_ != null || productVariant_ != null;
    }
    /**
     * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
     * @return The productVariant.
     */
    public com.minh.grpc.product_service.ProductVariant getProductVariant() {
      if (productVariantBuilder_ == null) {
        return productVariant_ == null ? com.minh.grpc.product_service.ProductVariant.getDefaultInstance() : productVariant_;
      } else {
        return productVariantBuilder_.getMessage();
      }
    }
    /**
     * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
     */
    public Builder setProductVariant(com.minh.grpc.product_service.ProductVariant value) {
      if (productVariantBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        productVariant_ = value;
        onChanged();
      } else {
        productVariantBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
     */
    public Builder setProductVariant(
        com.minh.grpc.product_service.ProductVariant.Builder builderForValue) {
      if (productVariantBuilder_ == null) {
        productVariant_ = builderForValue.build();
        onChanged();
      } else {
        productVariantBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
     */
    public Builder mergeProductVariant(com.minh.grpc.product_service.ProductVariant value) {
      if (productVariantBuilder_ == null) {
        if (productVariant_ != null) {
          productVariant_ =
            com.minh.grpc.product_service.ProductVariant.newBuilder(productVariant_).mergeFrom(value).buildPartial();
        } else {
          productVariant_ = value;
        }
        onChanged();
      } else {
        productVariantBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
     */
    public Builder clearProductVariant() {
      if (productVariantBuilder_ == null) {
        productVariant_ = null;
        onChanged();
      } else {
        productVariant_ = null;
        productVariantBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
     */
    public com.minh.grpc.product_service.ProductVariant.Builder getProductVariantBuilder() {
      
      onChanged();
      return getProductVariantFieldBuilder().getBuilder();
    }
    /**
     * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
     */
    public com.minh.grpc.product_service.ProductVariantOrBuilder getProductVariantOrBuilder() {
      if (productVariantBuilder_ != null) {
        return productVariantBuilder_.getMessageOrBuilder();
      } else {
        return productVariant_ == null ?
            com.minh.grpc.product_service.ProductVariant.getDefaultInstance() : productVariant_;
      }
    }
    /**
     * <code>.net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minh.grpc.product_service.ProductVariant, com.minh.grpc.product_service.ProductVariant.Builder, com.minh.grpc.product_service.ProductVariantOrBuilder> 
        getProductVariantFieldBuilder() {
      if (productVariantBuilder_ == null) {
        productVariantBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.minh.grpc.product_service.ProductVariant, com.minh.grpc.product_service.ProductVariant.Builder, com.minh.grpc.product_service.ProductVariantOrBuilder>(
                getProductVariant(),
                getParentForChildren(),
                isClean());
        productVariant_ = null;
      }
      return productVariantBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:net.devh.boot.grpc.example.FindProductVariantByIdResponse)
  }

  // @@protoc_insertion_point(class_scope:net.devh.boot.grpc.example.FindProductVariantByIdResponse)
  private static final com.minh.grpc.product_service.FindProductVariantByIdResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.minh.grpc.product_service.FindProductVariantByIdResponse();
  }

  public static com.minh.grpc.product_service.FindProductVariantByIdResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FindProductVariantByIdResponse>
      PARSER = new com.google.protobuf.AbstractParser<FindProductVariantByIdResponse>() {
    @java.lang.Override
    public FindProductVariantByIdResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FindProductVariantByIdResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FindProductVariantByIdResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.minh.grpc.product_service.FindProductVariantByIdResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

