// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.grpc.product_service;

public interface FindProductVariantsByIdsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.FindProductVariantsByIdsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
   */
  java.util.List<com.minh.grpc.product_service.ProductVariant> 
      getProductVariantList();
  /**
   * <code>repeated .net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
   */
  com.minh.grpc.product_service.ProductVariant getProductVariant(int index);
  /**
   * <code>repeated .net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
   */
  int getProductVariantCount();
  /**
   * <code>repeated .net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
   */
  java.util.List<? extends com.minh.grpc.product_service.ProductVariantOrBuilder> 
      getProductVariantOrBuilderList();
  /**
   * <code>repeated .net.devh.boot.grpc.example.ProductVariant productVariant = 3;</code>
   */
  com.minh.grpc.product_service.ProductVariantOrBuilder getProductVariantOrBuilder(
      int index);
}
