// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.minh.grpc.product_service;

public final class ProductProto {
  private ProductProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_ProductVariant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_ProductVariant_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_CartItemField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_CartItemField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\022\032net.devh.boot.grpc.exam" +
      "ple\"\264\001\n\016ProductVariant\022\n\n\002id\030\001 \001(\t\022\014\n\004na" +
      "me\030\002 \001(\t\022\014\n\004slug\030\003 \001(\t\022\014\n\004size\030\004 \001(\t\022\021\n\t" +
      "colorName\030\005 \001(\t\022\020\n\010colorHex\030\006 \001(\t\022\r\n\005cov" +
      "er\030\007 \001(\t\022\r\n\005price\030\010 \001(\001\022\025\n\roriginalPrice" +
      "\030\t \001(\001\022\022\n\ncartItemId\030\n \001(\t\"+\n\035FindProduc" +
      "tVariantByIdRequest\022\n\n\002id\030\001 \001(\t\"\205\001\n\036Find" +
      "ProductVariantByIdResponse\022\016\n\006status\030\001 \001" +
      "(\005\022\017\n\007message\030\002 \001(\t\022B\n\016productVariant\030\003 " +
      "\001(\0132*.net.devh.boot.grpc.example.Product" +
      "Variant\"=\n\rCartItemField\022\022\n\ncartItemId\030\001" +
      " \001(\t\022\030\n\020productVariantId\030\002 \001(\t\"c\n\037FindPr" +
      "oductVariantsByIdsRequest\022@\n\rcartItemFie" +
      "ld\030\001 \003(\0132).net.devh.boot.grpc.example.Ca" +
      "rtItemField\"\207\001\n FindProductVariantsByIds" +
      "Response\022\016\n\006status\030\001 \001(\005\022\017\n\007message\030\002 \001(" +
      "\t\022B\n\016productVariant\030\003 \003(\0132*.net.devh.boo" +
      "t.grpc.example.ProductVariant2\272\002\n\016Produc" +
      "tService\022\217\001\n\026FindProductVariantById\0229.ne" +
      "t.devh.boot.grpc.example.FindProductVari" +
      "antByIdRequest\032:.net.devh.boot.grpc.exam" +
      "ple.FindProductVariantByIdResponse\022\225\001\n\030F" +
      "indProductVariantsByIds\022;.net.devh.boot." +
      "grpc.example.FindProductVariantsByIdsReq" +
      "uest\032<.net.devh.boot.grpc.example.FindPr" +
      "oductVariantsByIdsResponseB/\n\035com.minh.g" +
      "rpc.product_serviceB\014ProductProtoP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_net_devh_boot_grpc_example_ProductVariant_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_devh_boot_grpc_example_ProductVariant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_ProductVariant_descriptor,
        new java.lang.String[] { "Id", "Name", "Slug", "Size", "ColorName", "ColorHex", "Cover", "Price", "OriginalPrice", "CartItemId", });
    internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_FindProductVariantByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_FindProductVariantByIdResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "ProductVariant", });
    internal_static_net_devh_boot_grpc_example_CartItemField_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_net_devh_boot_grpc_example_CartItemField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_CartItemField_descriptor,
        new java.lang.String[] { "CartItemId", "ProductVariantId", });
    internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsRequest_descriptor,
        new java.lang.String[] { "CartItemField", });
    internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_devh_boot_grpc_example_FindProductVariantsByIdsResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "ProductVariant", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
